### ISSUE TITLE
GNOME 47 Broken modal buttons

### ISSUE THREAD

**Issue by khaled-0** [imarkoff/Marble-shell-theme#42]
Only in light theme. Dark is fine
![image](https://github.com/user-attachments/assets/d20ce88f-ab54-464d-a359-343e11120f68)

**Comment by khaled-0** [comment]
> Can you try to install the theme from 47 branch? Maybe I've already solved this problem

nope, the switch is fixed but not these

**Comment by imarkoff** [comment]
Can you try to install the theme from 47 branch? Maybe I've already solved this problem

**Comment by sdandroid** [comment]
use 47 branch  still have problem.
![截图 2024-12-19 12-00-06](https://github.com/user-attachments/assets/00a19c88-ac4c-4a88-bbb4-1dc62cf57394)
